// autogenerated by syzkaller (http://github.com/google/syzkaller)

#ifndef __NR_bind
#define __NR_bind 49
#endif
#ifndef __NR_openat
#define __NR_openat 257
#endif
#ifndef __NR_creat
#define __NR_creat 85
#endif
#ifndef __NR_shutdown
#define __NR_shutdown 48
#endif
#ifndef __NR_symlinkat
#define __NR_symlinkat 266
#endif
#ifndef __NR_getsockopt
#define __NR_getsockopt 55
#endif
#ifndef __NR_syz_emit_ethernet
#define __NR_syz_emit_ethernet 1000006
#endif
#ifndef __NR_mmap
#define __NR_mmap 9
#endif
#ifndef __NR_connect
#define __NR_connect 42
#endif
#ifndef __NR_socket
#define __NR_socket 41
#endif

#define __STDC_VERSION__ 201112L

#define _GNU_SOURCE 

#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/resource.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>

#include <linux/capability.h>
#include <linux/if.h>
#include <linux/if_tun.h>
#include <linux/kvm.h>
#include <linux/sched.h>
#include <net/if_arp.h>

#include <assert.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <grp.h>
#include <pthread.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

const int kFailStatus = 67;
const int kErrorStatus = 68;
const int kRetryStatus = 69;

__attribute__((noreturn)) void doexit(int status)
{
	volatile unsigned i;
	syscall(__NR_exit_group, status);
	for (i = 0;; i++) {
	}
}

__attribute__((noreturn)) void fail(const char* msg, ...)
{
	int e = errno;
	fflush(stdout);
	va_list args;
	va_start(args, msg);
	vfprintf(stderr, msg, args);
	va_end(args);
	fprintf(stderr, " (errno %d)\n", e);
	doexit(e == ENOMEM ? kRetryStatus : kFailStatus);
}

__attribute__((noreturn)) void exitf(const char* msg, ...)
{
	int e = errno;
	fflush(stdout);
	va_list args;
	va_start(args, msg);
	vfprintf(stderr, msg, args);
	va_end(args);
	fprintf(stderr, " (errno %d)\n", e);
	doexit(kRetryStatus);
}

static int flag_debug;

void debug(const char* msg, ...)
{
	if (!flag_debug)
		return;
	va_list args;
	va_start(args, msg);
	vfprintf(stdout, msg, args);
	va_end(args);
	fflush(stdout);
}

__thread int skip_segv;
__thread jmp_buf segv_env;

static void segv_handler(int sig, siginfo_t* info, void* uctx)
{
	uintptr_t addr = (uintptr_t)info->si_addr;
	const uintptr_t prog_start = 1 << 20;
	const uintptr_t prog_end = 100 << 20;
	if (__atomic_load_n(&skip_segv, __ATOMIC_RELAXED) && (addr < prog_start || addr > prog_end)) {
		debug("SIGSEGV on %p, skipping\n", addr);
		_longjmp(segv_env, 1);
	}
	debug("SIGSEGV on %p, exiting\n", addr);
	doexit(sig);
	for (;;) {
	}
}

static void install_segv_handler()
{
	struct sigaction sa;
	memset(&sa, 0, sizeof(sa));
	sa.sa_sigaction = segv_handler;
	sa.sa_flags = SA_NODEFER | SA_SIGINFO;
	sigaction(SIGSEGV, &sa, NULL);
	sigaction(SIGBUS, &sa, NULL);
}

#define NONFAILING(...) { __atomic_fetch_add(&skip_segv, 1, __ATOMIC_SEQ_CST); if (_setjmp(segv_env) == 0) { __VA_ARGS__; } __atomic_fetch_sub(&skip_segv, 1, __ATOMIC_SEQ_CST); }

#define BITMASK_LEN(type,bf_len) (type)((1ull << (bf_len)) - 1)

#define BITMASK_LEN_OFF(type,bf_off,bf_len) (type)(BITMASK_LEN(type, (bf_len)) << (bf_off))

#define STORE_BY_BITMASK(type,addr,val,bf_off,bf_len) if ((bf_off) == 0 && (bf_len) == 0) { *(type*)(addr) = (type)(val); } else { type new_val = *(type*)(addr); new_val &= ~BITMASK_LEN_OFF(type, (bf_off), (bf_len)); new_val |= ((type)(val)&BITMASK_LEN(type, (bf_len))) << (bf_off); *(type*)(addr) = new_val; }

static void vsnprintf_check(char* str, size_t size, const char* format, va_list args)
{
	int rv;

	rv = vsnprintf(str, size, format, args);
	if (rv < 0)
		fail("tun: snprintf failed");
	if ((size_t)rv >= size)
		fail("tun: string '%s...' doesn't fit into buffer", str);
}

static void snprintf_check(char* str, size_t size, const char* format, ...)
{
	va_list args;

	va_start(args, format);
	vsnprintf_check(str, size, format, args);
	va_end(args);
}

#define COMMAND_MAX_LEN 128

static void execute_command(const char* format, ...)
{
	va_list args;
	char command[COMMAND_MAX_LEN];
	int rv;

	va_start(args, format);

	vsnprintf_check(command, sizeof(command), format, args);
	rv = system(command);
	if (rv != 0)
		fail("tun: command \"%s\" failed with code %d", &command[0], rv);

	va_end(args);
}

int tunfd = -1;

#define MAX_PIDS 32
#define ADDR_MAX_LEN 32

#define LOCAL_MAC "aa:aa:aa:aa:aa:%02hx"
#define REMOTE_MAC "bb:bb:bb:bb:bb:%02hx"

#define LOCAL_IPV4 "172.20.%d.170"
#define REMOTE_IPV4 "172.20.%d.187"

#define LOCAL_IPV6 "fd00::%02hxaa"
#define REMOTE_IPV6 "fd00::%02hxbb"

static void initialize_tun(uint64_t pid)
{
	if (pid >= MAX_PIDS)
		fail("tun: no more than %d executors", MAX_PIDS);
	int id = pid;

	tunfd = open("/dev/net/tun", O_RDWR);
	if (tunfd == -1)
		fail("tun: can't open /dev/net/tun");

	char iface[IFNAMSIZ];
	snprintf_check(iface, sizeof(iface), "syz%d", id);

	struct ifreq ifr;
	memset(&ifr, 0, sizeof(ifr));
	strncpy(ifr.ifr_name, iface, IFNAMSIZ);
	ifr.ifr_flags = IFF_TAP | IFF_NO_PI;
	if (ioctl(tunfd, TUNSETIFF, (void*)&ifr) < 0)
		fail("tun: ioctl(TUNSETIFF) failed");

	char local_mac[ADDR_MAX_LEN];
	snprintf_check(local_mac, sizeof(local_mac), LOCAL_MAC, id);
	char remote_mac[ADDR_MAX_LEN];
	snprintf_check(remote_mac, sizeof(remote_mac), REMOTE_MAC, id);

	char local_ipv4[ADDR_MAX_LEN];
	snprintf_check(local_ipv4, sizeof(local_ipv4), LOCAL_IPV4, id);
	char remote_ipv4[ADDR_MAX_LEN];
	snprintf_check(remote_ipv4, sizeof(remote_ipv4), REMOTE_IPV4, id);

	char local_ipv6[ADDR_MAX_LEN];
	snprintf_check(local_ipv6, sizeof(local_ipv6), LOCAL_IPV6, id);
	char remote_ipv6[ADDR_MAX_LEN];
	snprintf_check(remote_ipv6, sizeof(remote_ipv6), REMOTE_IPV6, id);

	execute_command("ip link set dev %s address %s", iface, local_mac);
	execute_command("ip addr add %s/24 dev %s", local_ipv4, iface);
	execute_command("ip -6 addr add %s/120 dev %s", local_ipv6, iface);
	execute_command("ip neigh add %s lladdr %s dev %s nud permanent", remote_ipv4, remote_mac, iface);
	execute_command("ip -6 neigh add %s lladdr %s dev %s nud permanent", remote_ipv6, remote_mac, iface);
	execute_command("ip link set %s up", iface);
}

static void setup_tun(uint64_t pid, bool enable_tun)
{
	if (enable_tun)
		initialize_tun(pid);
}

static uintptr_t syz_emit_ethernet(uintptr_t a0, uintptr_t a1)
{
	if (tunfd < 0)
		return (uintptr_t)-1;

	int64_t length = a0;
	char* data = (char*)a1;
	return write(tunfd, data, length);
}

static uintptr_t execute_syscall(int nr, uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5, uintptr_t a6, uintptr_t a7, uintptr_t a8)
{
	switch (nr) {
	default:
		return syscall(nr, a0, a1, a2, a3, a4, a5);
	case __NR_syz_emit_ethernet:
		return syz_emit_ethernet(a0, a1);
	}
}

static void setup_main_process()
{
	struct sigaction sa;
	memset(&sa, 0, sizeof(sa));
	sa.sa_handler = SIG_IGN;
	syscall(SYS_rt_sigaction, 0x20, &sa, NULL, 8);
	syscall(SYS_rt_sigaction, 0x21, &sa, NULL, 8);
	install_segv_handler();

	char tmpdir_template[] = "./syzkaller.XXXXXX";
	char* tmpdir = mkdtemp(tmpdir_template);
	if (!tmpdir)
		fail("failed to mkdtemp");
	if (chmod(tmpdir, 0777))
		fail("failed to chmod");
	if (chdir(tmpdir))
		fail("failed to chdir");
}

static void loop();

static void sandbox_common()
{
	prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
	setpgrp();
	setsid();

	struct rlimit rlim;
	rlim.rlim_cur = rlim.rlim_max = 128 << 20;
	setrlimit(RLIMIT_AS, &rlim);
	rlim.rlim_cur = rlim.rlim_max = 1 << 20;
	setrlimit(RLIMIT_FSIZE, &rlim);
	rlim.rlim_cur = rlim.rlim_max = 1 << 20;
	setrlimit(RLIMIT_STACK, &rlim);
	rlim.rlim_cur = rlim.rlim_max = 0;
	setrlimit(RLIMIT_CORE, &rlim);

	unshare(CLONE_NEWNS);
	unshare(CLONE_NEWIPC);
	unshare(CLONE_IO);
}

static int do_sandbox_none(int executor_pid, bool enable_tun)
{
	int pid = fork();
	if (pid)
		return pid;

	sandbox_common();
	setup_tun(executor_pid, enable_tun);

	loop();
	doexit(1);
}

long r[113];
void loop()
{
	memset(r, -1, sizeof(r));
	r[0] = execute_syscall(__NR_mmap, 0x20000000ul, 0x1f9000ul, 0x3ul, 0x32ul, 0xfffffffffffffffful, 0x0ul, 0, 0, 0);
	r[1] = execute_syscall(__NR_socket, 0x2ul, 0x1ul, 0x0ul, 0, 0, 0, 0, 0, 0);
	NONFAILING(*(uint16_t*)0x20101000 = (uint16_t)0x2);
	NONFAILING(*(uint16_t*)0x20101002 = (uint16_t)0x204e);
	NONFAILING(*(uint32_t*)0x20101004 = (uint32_t)0x0);
	NONFAILING(*(uint8_t*)0x20101008 = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x20101009 = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x2010100a = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x2010100b = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x2010100c = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x2010100d = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x2010100e = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x2010100f = (uint8_t)0x0);
	r[13] = execute_syscall(__NR_bind, r[1], 0x20101000ul, 0x10ul, 0, 0, 0, 0, 0, 0);
	r[14] = execute_syscall(__NR_mmap, 0x201f9000ul, 0x1000ul, 0x3ul, 0x32ul, 0xfffffffffffffffful, 0x0ul, 0, 0, 0);
	r[15] = execute_syscall(__NR_mmap, 0x201fa000ul, 0x1000ul, 0x3ul, 0x32ul, 0xfffffffffffffffful, 0x0ul, 0, 0, 0);
	r[16] = execute_syscall(__NR_mmap, 0x201fa000ul, 0x1000ul, 0x3ul, 0x32ul, 0xfffffffffffffffful, 0x0ul, 0, 0, 0);
	r[17] = execute_syscall(__NR_mmap, 0x201fb000ul, 0x1000ul, 0x3ul, 0x32ul, 0xfffffffffffffffful, 0x0ul, 0, 0, 0);
	NONFAILING(memcpy((void*)0x200ba000, "\x2f\x64\x65\x76\x2f\x73\x65\x71\x75\x65\x6e\x63\x65\x72\x32\x00", 16));
	r[19] = execute_syscall(__NR_openat, 0xffffffffffffff9cul, 0x200ba000ul, 0x8600ul, 0x0ul, 0, 0, 0, 0, 0);
	r[20] = execute_syscall(__NR_mmap, 0x2017e000ul, 0x3000ul, 0x3ul, 0x32ul, r[19], 0x4ul, 0, 0, 0);
	NONFAILING(memcpy((void*)0x201fc000, "\x2e\x2f\x66\x69\x6c\x65\x30\x00", 8));
	r[22] = execute_syscall(__NR_creat, 0x201fc000ul, 0x2ul, 0, 0, 0, 0, 0, 0, 0);
	r[23] = execute_syscall(__NR_shutdown, r[19], 0x1ul, 0, 0, 0, 0, 0, 0, 0);
	r[24] = execute_syscall(__NR_mmap, 0x201fb000ul, 0x1000ul, 0x3ul, 0x32ul, 0xfffffffffffffffful, 0x0ul, 0, 0, 0);
	NONFAILING(memcpy((void*)0x201fb000, "\x2e\x2f\x66\x69\x6c\x65\x30\x00", 8));
	NONFAILING(memcpy((void*)0x201fb000, "\x2e\x2f\x66\x69\x6c\x65\x30\x00", 8));
	r[27] = execute_syscall(__NR_symlinkat, 0x201fb000ul, r[19], 0x201fb000ul, 0, 0, 0, 0, 0, 0);
	NONFAILING(*(uint32_t*)0x201faffc = (uint32_t)0x4);
	r[29] = execute_syscall(__NR_getsockopt, r[1], 0x0ul, 0x0ul, 0x201fa000ul, 0x201faffcul, 0, 0, 0, 0);
	NONFAILING(*(uint16_t*)0x201f9ff0 = (uint16_t)0x2);
	NONFAILING(*(uint16_t*)0x201f9ff2 = (uint16_t)0x204e);
	NONFAILING(*(uint32_t*)0x201f9ff4 = (uint32_t)0x100007f);
	NONFAILING(*(uint8_t*)0x201f9ff8 = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x201f9ff9 = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x201f9ffa = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x201f9ffb = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x201f9ffc = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x201f9ffd = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x201f9ffe = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x201f9fff = (uint8_t)0x0);
	r[41] = execute_syscall(__NR_connect, r[1], 0x201f9ff0ul, 0x10ul, 0, 0, 0, 0, 0, 0);
	r[42] = execute_syscall(__NR_socket, 0x2ul, 0x0ul, 0x84ul, 0, 0, 0, 0, 0, 0);
	NONFAILING(*(uint32_t*)0x201f4ff4 = (uint32_t)0x400);
	NONFAILING(*(uint32_t*)0x201f4ff8 = (uint32_t)0x9b);
	NONFAILING(*(uint8_t*)0x201f4ffc = (uint8_t)0x6);
	NONFAILING(*(uint32_t*)0x20016000 = (uint32_t)0xc);
	r[47] = execute_syscall(__NR_getsockopt, r[42], 0x84ul, 0x6cul, 0x201f4ff4ul, 0x20016000ul, 0, 0, 0, 0);
	NONFAILING(*(uint8_t*)0x20000000 = (uint8_t)0xaa);
	NONFAILING(*(uint8_t*)0x20000001 = (uint8_t)0xaa);
	NONFAILING(*(uint8_t*)0x20000002 = (uint8_t)0xaa);
	NONFAILING(*(uint8_t*)0x20000003 = (uint8_t)0xaa);
	NONFAILING(*(uint8_t*)0x20000004 = (uint8_t)0xaa);
	NONFAILING(*(uint8_t*)0x20000005 = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x20000006 = (uint8_t)0xbb);
	NONFAILING(*(uint8_t*)0x20000007 = (uint8_t)0xbb);
	NONFAILING(*(uint8_t*)0x20000008 = (uint8_t)0xbb);
	NONFAILING(*(uint8_t*)0x20000009 = (uint8_t)0xbb);
	NONFAILING(*(uint8_t*)0x2000000a = (uint8_t)0xbb);
	NONFAILING(*(uint8_t*)0x2000000b = (uint8_t)0x0);
	NONFAILING(*(uint16_t*)0x2000000c = (uint16_t)0x8);
	NONFAILING(STORE_BY_BITMASK(uint8_t, 0x2000000e, 0x5, 0, 4));
	NONFAILING(STORE_BY_BITMASK(uint8_t, 0x2000000e, 0x4, 4, 4));
	NONFAILING(STORE_BY_BITMASK(uint8_t, 0x2000000f, 0x0, 0, 2));
	NONFAILING(STORE_BY_BITMASK(uint8_t, 0x2000000f, 0x0, 2, 6));
	NONFAILING(*(uint16_t*)0x20000010 = (uint16_t)0x6400);
	NONFAILING(*(uint16_t*)0x20000012 = (uint16_t)0x0);
	NONFAILING(*(uint16_t*)0x20000014 = (uint16_t)0x0);
	NONFAILING(*(uint8_t*)0x20000016 = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x20000017 = (uint8_t)0x2f);
	NONFAILING(*(uint16_t*)0x20000018 = (uint16_t)0xde60);
	NONFAILING(*(uint8_t*)0x2000001a = (uint8_t)0xac);
	NONFAILING(*(uint8_t*)0x2000001b = (uint8_t)0x14);
	NONFAILING(*(uint8_t*)0x2000001c = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x2000001d = (uint8_t)0xbb);
	NONFAILING(*(uint8_t*)0x2000001e = (uint8_t)0xac);
	NONFAILING(*(uint8_t*)0x2000001f = (uint8_t)0x14);
	NONFAILING(*(uint8_t*)0x20000020 = (uint8_t)0x0);
	NONFAILING(*(uint8_t*)0x20000021 = (uint8_t)0xaa);
	NONFAILING(*(uint16_t*)0x20000022 = (uint16_t)0x204e);
	NONFAILING(*(uint16_t*)0x20000024 = (uint16_t)0x204e);
	NONFAILING(*(uint32_t*)0x20000026 = (uint32_t)0xfcffffff);
	NONFAILING(*(uint32_t*)0x2000002a = (uint32_t)0x56565656);
	NONFAILING(STORE_BY_BITMASK(uint8_t, 0x2000002e, 0x0, 0, 1));
	NONFAILING(STORE_BY_BITMASK(uint8_t, 0x2000002e, 0x0, 1, 3));
	NONFAILING(STORE_BY_BITMASK(uint8_t, 0x2000002e, 0x14, 4, 4));
	NONFAILING(*(uint8_t*)0x2000002f = (uint8_t)0x2);
	NONFAILING(*(uint16_t*)0x20000030 = (uint16_t)0x0);
	NONFAILING(*(uint16_t*)0x20000032 = (uint16_t)0xfe17);
	NONFAILING(*(uint16_t*)0x20000034 = (uint16_t)0x0);
	NONFAILING(*(uint8_t*)0x20000036 = (uint8_t)0x2);
	NONFAILING(*(uint8_t*)0x20000037 = (uint8_t)0x4);
	NONFAILING(*(uint16_t*)0x20000038 = (uint16_t)0x1000);
	NONFAILING(*(uint8_t*)0x2000003a = (uint8_t)0x8);
	NONFAILING(*(uint8_t*)0x2000003b = (uint8_t)0xa);
	NONFAILING(*(uint32_t*)0x2000003c = (uint32_t)0x9000000);
	NONFAILING(*(uint32_t*)0x20000040 = (uint32_t)0x0);
	NONFAILING(*(uint8_t*)0x20000044 = (uint8_t)0x3);
	NONFAILING(*(uint8_t*)0x20000045 = (uint8_t)0x3);
	NONFAILING(*(uint8_t*)0x20000046 = (uint8_t)0x9);
	NONFAILING(*(uint8_t*)0x20000047 = (uint8_t)0x5);
	NONFAILING(*(uint8_t*)0x20000048 = (uint8_t)0x2a);
	NONFAILING(*(uint32_t*)0x20000049 = (uint32_t)0x1000000);
	NONFAILING(*(uint32_t*)0x2000004d = (uint32_t)0x4000000);
	NONFAILING(*(uint32_t*)0x20000051 = (uint32_t)0x0);
	NONFAILING(*(uint32_t*)0x20000055 = (uint32_t)0x9b000000);
	NONFAILING(*(uint32_t*)0x20000059 = (uint32_t)0x55000000);
	NONFAILING(*(uint32_t*)0x2000005d = (uint32_t)0x0);
	NONFAILING(*(uint32_t*)0x20000061 = (uint32_t)0x7000000);
	NONFAILING(*(uint32_t*)0x20000065 = (uint32_t)0x8000000);
	NONFAILING(*(uint32_t*)0x20000069 = (uint32_t)0x5000000);
	NONFAILING(*(uint32_t*)0x2000006d = (uint32_t)0xbc000000);
	r[112] = execute_syscall(__NR_syz_emit_ethernet, 0x72ul, 0x20000000ul, 0, 0, 0, 0, 0, 0, 0);
}
int main()
{
	setup_main_process();
	int pid = do_sandbox_none(0, true);
	int status = 0;
	while (waitpid(pid, &status, __WALL) != pid) {}
	return 0;
}
