// autogenerated by syzkaller (http://github.com/google/syzkaller)

#ifndef __NR_mmap
#define __NR_mmap 9
#endif
#ifndef __NR_inotify_add_watch
#define __NR_inotify_add_watch 254
#endif
#ifndef __NR_getsockopt
#define __NR_getsockopt 55
#endif
#ifndef __NR_ioctl
#define __NR_ioctl 16
#endif
#ifndef __NR_bind
#define __NR_bind 49
#endif
#ifndef __NR_inotify_init1
#define __NR_inotify_init1 294
#endif
#ifndef __NR_fcntl
#define __NR_fcntl 72
#endif
#ifndef __NR_ptrace
#define __NR_ptrace 101
#endif
#ifndef __NR_dup3
#define __NR_dup3 292
#endif
#ifndef __NR_open
#define __NR_open 2
#endif

#define __STDC_VERSION__ 201112L

#define _GNU_SOURCE 

#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/resource.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>

#include <linux/capability.h>
#include <linux/if.h>
#include <linux/if_tun.h>
#include <linux/kvm.h>
#include <linux/sched.h>
#include <net/if_arp.h>

#include <assert.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <grp.h>
#include <pthread.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

const int kFailStatus = 67;
const int kErrorStatus = 68;
const int kRetryStatus = 69;

__attribute__((noreturn)) void doexit(int status)
{
	volatile unsigned i;
	syscall(__NR_exit_group, status);
	for (i = 0;; i++) {
	}
}

__attribute__((noreturn)) void fail(const char* msg, ...)
{
	int e = errno;
	fflush(stdout);
	va_list args;
	va_start(args, msg);
	vfprintf(stderr, msg, args);
	va_end(args);
	fprintf(stderr, " (errno %d)\n", e);
	doexit(e == ENOMEM ? kRetryStatus : kFailStatus);
}

__attribute__((noreturn)) void exitf(const char* msg, ...)
{
	int e = errno;
	fflush(stdout);
	va_list args;
	va_start(args, msg);
	vfprintf(stderr, msg, args);
	va_end(args);
	fprintf(stderr, " (errno %d)\n", e);
	doexit(kRetryStatus);
}

static int flag_debug;

void debug(const char* msg, ...)
{
	if (!flag_debug)
		return;
	va_list args;
	va_start(args, msg);
	vfprintf(stdout, msg, args);
	va_end(args);
	fflush(stdout);
}

__thread int skip_segv;
__thread jmp_buf segv_env;

static void segv_handler(int sig, siginfo_t* info, void* uctx)
{
	uintptr_t addr = (uintptr_t)info->si_addr;
	const uintptr_t prog_start = 1 << 20;
	const uintptr_t prog_end = 100 << 20;
	if (__atomic_load_n(&skip_segv, __ATOMIC_RELAXED) && (addr < prog_start || addr > prog_end)) {
		debug("SIGSEGV on %p, skipping\n", addr);
		_longjmp(segv_env, 1);
	}
	debug("SIGSEGV on %p, exiting\n", addr);
	doexit(sig);
	for (;;) {
	}
}

static void install_segv_handler()
{
	struct sigaction sa;
	memset(&sa, 0, sizeof(sa));
	sa.sa_sigaction = segv_handler;
	sa.sa_flags = SA_NODEFER | SA_SIGINFO;
	sigaction(SIGSEGV, &sa, NULL);
	sigaction(SIGBUS, &sa, NULL);
}

#define NONFAILING(...) { __atomic_fetch_add(&skip_segv, 1, __ATOMIC_SEQ_CST); if (_setjmp(segv_env) == 0) { __VA_ARGS__; } __atomic_fetch_sub(&skip_segv, 1, __ATOMIC_SEQ_CST); }

#define BITMASK_LEN(type,bf_len) (type)((1ull << (bf_len)) - 1)

#define BITMASK_LEN_OFF(type,bf_off,bf_len) (type)(BITMASK_LEN(type, (bf_len)) << (bf_off))

#define STORE_BY_BITMASK(type,addr,val,bf_off,bf_len) if ((bf_off) == 0 && (bf_len) == 0) { *(type*)(addr) = (type)(val); } else { type new_val = *(type*)(addr); new_val &= ~BITMASK_LEN_OFF(type, (bf_off), (bf_len)); new_val |= ((type)(val)&BITMASK_LEN(type, (bf_len))) << (bf_off); *(type*)(addr) = new_val; }

static uintptr_t execute_syscall(int nr, uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4, uintptr_t a5, uintptr_t a6, uintptr_t a7, uintptr_t a8)
{
	switch (nr) {
	default:
		return syscall(nr, a0, a1, a2, a3, a4, a5);
	}
}

static void setup_main_process()
{
	struct sigaction sa;
	memset(&sa, 0, sizeof(sa));
	sa.sa_handler = SIG_IGN;
	syscall(SYS_rt_sigaction, 0x20, &sa, NULL, 8);
	syscall(SYS_rt_sigaction, 0x21, &sa, NULL, 8);
	install_segv_handler();

	char tmpdir_template[] = "./syzkaller.XXXXXX";
	char* tmpdir = mkdtemp(tmpdir_template);
	if (!tmpdir)
		fail("failed to mkdtemp");
	if (chmod(tmpdir, 0777))
		fail("failed to chmod");
	if (chdir(tmpdir))
		fail("failed to chdir");
}

static void loop();

static void sandbox_common()
{
	prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
	setpgrp();
	setsid();

	struct rlimit rlim;
	rlim.rlim_cur = rlim.rlim_max = 128 << 20;
	setrlimit(RLIMIT_AS, &rlim);
	rlim.rlim_cur = rlim.rlim_max = 1 << 20;
	setrlimit(RLIMIT_FSIZE, &rlim);
	rlim.rlim_cur = rlim.rlim_max = 1 << 20;
	setrlimit(RLIMIT_STACK, &rlim);
	rlim.rlim_cur = rlim.rlim_max = 0;
	setrlimit(RLIMIT_CORE, &rlim);

	unshare(CLONE_NEWNS);
	unshare(CLONE_NEWIPC);
	unshare(CLONE_IO);
}

static int do_sandbox_none(int executor_pid, bool enable_tun)
{
	int pid = fork();
	if (pid)
		return pid;

	sandbox_common();

	loop();
	doexit(1);
}

long r[35];
void loop()
{
	memset(r, -1, sizeof(r));
	r[0] = execute_syscall(__NR_mmap, 0x20000000ul, 0x4000ul, 0x3ul, 0x32ul, 0xfffffffffffffffful, 0x0ul, 0, 0, 0);
	r[1] = execute_syscall(__NR_inotify_init1, 0x0ul, 0, 0, 0, 0, 0, 0, 0, 0);
	NONFAILING(memcpy((void*)0x20003ffa, "\x2e\x2f\x63\x6f\x6e\x74\x72\x6f\x6c\x00", 10));
	r[3] = execute_syscall(__NR_inotify_add_watch, r[1], 0x20003ffaul, 0x20000100ul, 0, 0, 0, 0, 0, 0);
	NONFAILING(*(uint32_t*)0x20006000 = (uint32_t)0xc);
	r[5] = execute_syscall(__NR_getsockopt, 0xfffffffffffffffful, 0x1ul, 0x11ul, 0x20006ff4ul, 0x20006000ul, 0, 0, 0, 0);
	if (r[5] != -1)
		NONFAILING(r[6] = *(uint32_t*)0x20006ff4);
	r[7] = execute_syscall(__NR_mmap, 0x20000000ul, 0xe6a000ul, 0x3ul, 0x32ul, 0xfffffffffffffffful, 0x0ul, 0, 0, 0);
	r[8] = execute_syscall(__NR_inotify_init1, 0x0ul, 0, 0, 0, 0, 0, 0, 0, 0);
	NONFAILING(*(uint32_t*)0x20048000 = (uint32_t)0xc);
	r[10] = execute_syscall(__NR_getsockopt, r[8], 0x1ul, 0x11ul, 0x2003cff4ul, 0x20048000ul, 0, 0, 0, 0);
	if (r[10] != -1)
		NONFAILING(r[11] = *(uint32_t*)0x2003cff4);
	r[12] = execute_syscall(__NR_fcntl, r[8], 0x8ul, r[11], 0, 0, 0, 0, 0, 0);
	r[13] = execute_syscall(__NR_fcntl, r[8], 0x10ul, 0x20c2c000ul, 0, 0, 0, 0, 0, 0);
	if (r[13] != -1)
		NONFAILING(r[14] = *(uint32_t*)0x20c2c004);
	r[15] = execute_syscall(__NR_ptrace, 0x4206ul, r[14], 0x0ul, 0x0ul, 0, 0, 0, 0, 0);
	r[16] = execute_syscall(__NR_ptrace, 0x4207ul, r[14], 0, 0, 0, 0, 0, 0, 0);
	r[17] = execute_syscall(__NR_fcntl, r[1], 0xaul, 0x12ul, 0, 0, 0, 0, 0, 0);
	r[18] = execute_syscall(__NR_fcntl, r[1], 0x8ul, r[6], 0, 0, 0, 0, 0, 0);
	r[19] = execute_syscall(__NR_dup3, r[1], r[1], 0x80000ul, 0, 0, 0, 0, 0, 0);
	r[20] = execute_syscall(__NR_ioctl, r[19], 0x5419ul, 0x20594ffcul, 0, 0, 0, 0, 0, 0);
	r[21] = execute_syscall(__NR_fcntl, r[1], 0x4ul, 0x2000ul, 0, 0, 0, 0, 0, 0);
	NONFAILING(memcpy((void*)0x20002000, "\x2e\x2f\x62\x75\x73\x00", 6));
	r[23] = execute_syscall(__NR_open, 0x20002000ul, 0x141042ul, 0x0ul, 0, 0, 0, 0, 0, 0);
	r[24] = execute_syscall(__NR_mmap, 0x20e6a000ul, 0x1000ul, 0x3ul, 0x32ul, 0xfffffffffffffffful, 0x0ul, 0, 0, 0);
	r[25] = execute_syscall(__NR_mmap, 0x20e6b000ul, 0x1000ul, 0x3ul, 0x32ul, 0xfffffffffffffffful, 0x0ul, 0, 0, 0);
	NONFAILING(*(uint16_t*)0x20e6b000 = (uint16_t)0x6);
	NONFAILING(memcpy((void*)0x20e6b002, "\x8d\xa1\x61\xd7\xc8\x4e\x68", 7));
	NONFAILING(*(uint32_t*)0x20e6b00c = (uint32_t)0x3);
	r[29] = execute_syscall(__NR_bind, r[23], 0x20e6b000ul, 0x10ul, 0, 0, 0, 0, 0, 0);
	r[30] = execute_syscall(__NR_mmap, 0x20e6a000ul, 0x1000ul, 0x3ul, 0x32ul, 0xfffffffffffffffful, 0x0ul, 0, 0, 0);
	NONFAILING(*(uint32_t*)0x20e6aff8 = (uint32_t)0x8001);
	NONFAILING(*(uint16_t*)0x20e6affc = (uint16_t)0xffffffff);
	NONFAILING(*(uint32_t*)0x20e6a000 = (uint32_t)0x8);
	r[34] = execute_syscall(__NR_getsockopt, r[23], 0x84ul, 0x18ul, 0x20e6aff8ul, 0x20e6a000ul, 0, 0, 0, 0);
}
int main()
{
	setup_main_process();
	int pid = do_sandbox_none(0, false);
	int status = 0;
	while (waitpid(pid, &status, __WALL) != pid) {}
	return 0;
}
